# Generated by Django 3.0.3 on 2020-03-06 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClientUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('start', models.CharField(max_length=25)),
                ('end', models.CharField(max_length=25)),
                ('image', models.CharField(max_length=110)),
                ('vendors', models.CharField(max_length=41)),
                ('terms', models.CharField(max_length=4315)),
                ('category', models.CharField(max_length=126)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.ManyToManyField(to='deals.Choices')),
                ('clientuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.ClientUsers')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.Deals')),
            ],
            options={
                'unique_together': {('clientuser', 'deal')},
            },
        ),
        migrations.CreateModel(
            name='BlackLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientuser1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientuser1', to='deals.ClientUsers')),
                ('clientuser2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientuser2', to='deals.ClientUsers')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.Deals')),
            ],
            options={
                'unique_together': {('clientuser2', 'clientuser1', 'deal')},
            },
        ),
    ]
