# Generated by Django 3.0.3 on 2020-03-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blacklists',
            unique_together={('clientuser2', 'clientuser1')},
        ),
        migrations.RemoveField(
            model_name='blacklists',
            name='deal',
        ),
    ]
